version: '3.9'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
